name: Build Dalamud
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: build_dalamud_${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build on Windows
    permissions:
      id-token: write
      contents: read
      attestations: write
    runs-on: windows-2022
    steps:
      - name: Checkout Dalamud
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'

          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build Dalamud
        run: .\build.ps1 compile
      - name: Test Dalamud
        run: .\build.ps1 test
      - name: Create hashlist
        run: .\CreateHashList.ps1 .\bin\Release
      - name: Attest Build
        if: github.event_name == 'push'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            bin/Release/hashes.json
            bin/Release/Dalamud.dll
            bin/Release/DalamudCrashHandler.exe
            bin/Release/Dalamud.*.dll
            bin/Release/Dalamud.*.exe
            bin/Release/FFXIVClientStructs.dll
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dalamud-artifact
          path: bin\Release