name: Gitee repos mirror periodic job
on:
  push:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.08
      with:
        # Gitee对应的秘钥
        private_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        github_org: Bluefissure
        gitee_org: Bluefissure
